version: "3.9"
services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - ./CHATapp:/usr/CHATapp/app/node_modules
    command: npm run start